Repository UTNkar/ordsys, pull requests merged in 2021-07, with the labels that each got.

#115 Add permissions to staff
  backend/admin.py
Labels: python

#119 Make claim and deliver not mutually exclusive
  frontend/src/components/Bar/OrderDetail.tsx
Labels: javascript

#97 Frontend now proxies the backend
  frontend/package.json
  frontend/src/api/DjangoBackend.ts
  frontend/src/setupProxy.js
  ordsys/settings/base.py
  ordsys/urls.py
Labels: javascript, python
