Repository UTNkar/ordsys, pull requests merged in 2021-06, with the labels that each got.

#90 Switch url patterns
  ordsys/urls.py
Labels: bug, python

#91 Change bulk_save to normal save
  backend/serializers.py
  backend/signals.py
Labels: bug, python

#92 Fix error with snackbar provider
  frontend/src/components/App.tsx
Labels: bug, javascript

#89 Change dev db engine to sqlite
  .env-template
  .gitignore
  README.md
  ordsys/settings/base.py
  ordsys/settings/dev.py
  ordsys/settings/production.py
  production-requirements.txt
  requirements.txt
Labels: python

#96 Add model declaration to admin.py
  backend/admin.py
Labels: bug
